#!/bin/sh
#
# @name KiteX Octocopter h geometry
#
# @type Octorotor h
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 motor 5
# @output MAIN6 motor 6
# @output MAIN7 motor 7
# @output MAIN8 motor 8
#
#
# @maintainer Andreas Okholm <andreas@kitex.tech>
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
  param set MC_PITCH_P 6
  param set MC_PITCHRATE_P 0.2
	# param set MC_ROLL_P 6.5
	param set MC_ROLLRATE_P 0.3

	param set MIS_TAKEOFF_ALT 10
  # number of the motors of the VTOL
	param set VT_MOT_COUNT 8
  param set VT_IDLE_PWM_MC  1080
	# type of the vtol
	# 3 is KITE
	param set VT_TYPE 3
	param set RTL_DESCEND_ALT 10.0
	param set RTL_LAND_DELAY 0
  param set V19_VT_ROLLDIR 0

  param set ELEVON_OVERIDE 0
  param set ELEVATOR_STATE 

  #  rudder and elevator values that we always need, add them here too! Not just init posix

  # Test. If it works, make another file with the calibration values
  param set CAL_ACC0_XOFF	2.039332389831542969


fi
# This is special kitex VTOL ( from now it has to be always 22)
set MAV_TYPE 22
# kitex special H configuration for the mixer
set MIXER kx4
set MIXER_AUX kx4
