#!/bin/sh
#
# @name KX4 VTOL
#
# @type MODIFIED VTOL
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
	# battery configuration 3 cells
	# param set BAT_N_CELLS 3
	# sensor calibration data

	# param set CAL_ACC0_ID 1376264
	# param set CAL_ACC0_XOFF 0.01
	# param set CAL_ACC0_XSCALE 1.01
	# param set CAL_ACC0_YOFF -0.01
	# param set CAL_ACC0_YSCALE 1.01
	# param set CAL_ACC0_ZOFF 0.01
	# param set CAL_ACC0_ZSCALE 1.01
	# param set CAL_ACC1_ID 1310728
	# param set CAL_ACC1_XOFF 0.01
	# param set CAL_GYRO0_ID 2293768
	# param set CAL_GYRO0_XOFF 0.01
	# param set CAL_MAG0_ID 196616
	# param set CAL_MAG0_XOFF 0.01

	# timeout for disarm after landing

	# param set COM_DISARM_LAND 5

	# RC control input
	# ----------------------------
	#0: RC Transmitter
	#1: Joystick/No RC Checks
	#2: Virtual RC by Joystick
	# ----------------------------
	# param set COM_RC_IN_MODE 1
	# # some EKF configurations
	# param set EKF2_ANGERR_INIT 0.01
	# param set EKF2_GBIAS_INIT 0.01
	# param set EKF2_MAG_TYPE 1
	# select the main source of the height estimation
	# ----------------------------
	#0: Barometric pressure
	#1: GPS
	#2: Range sensor
	#3: Vision
	# ----------------------------
	# param set EKF2_HGT_MODE 0
	#
	#
	# param set FW_AIRSPD_MAX 25
	# param set FW_AIRSPD_MIN 14
	# param set FW_AIRSPD_TRIM 16
	#
	# param set MC_PITCH_P 6
	# param set MC_PITCHRATE_P 0.2
	# param set MC_ROLL_P 6
	# param set MC_ROLLRATE_P 0.3
	#
	# param set MIS_LTRMIN_ALT 10
	# param set MIS_TAKEOFF_ALT 10
	# param set MIS_YAW_TMT 10
	#
	# param set MPC_ACC_HOR_MAX 2
	# param set MPC_ACC_HOR_MAX 2
	# param set MPC_THR_MIN 0.1
	# param set MPC_TKO_SPEED 1
	# param set MPC_XY_P 0.8
	# param set MPC_XY_VEL_D 0.005
	# param set MPC_XY_VEL_I 0.2
	# param set MPC_XY_VEL_P 0.15
	# param set MPC_Z_VEL_MAX_DN 1.5
	# param set MPC_Z_VEL_P 0.6
	#
	# param set NAV_ACC_RAD 5
	# param set NAV_LOITER_RAD 80
	# param set NAV_DLL_ACT 2
	#
	# param set VT_F_TRANS_DUR 5
	# param set VT_F_TRANS_THR 0.75
  # number of the motors of the VTOL
	param set VT_MOT_COUNT 8 # This is where we set the motor count
	# param set VT_IDLE_PWM_MC  1080
	# type of the vtol
	# 3 is KITE
	param set VT_TYPE 1
	#
	# param set RTL_DESCEND_ALT 10.0
	# param set RTL_LAND_DELAY 0
	# param set RTL_RETURN_ALT 30.0
	#
	# param set SENS_BOARD_ROT 0
	# param set SENS_BOARD_X_OFF 0.000001
	# param set SENS_DPRES_OFF 0.001

	param set SYS_AUTOSTART 1120
	# param set SYS_MC_EST_GROUP 2
	# param set SYS_RESTART_TYPE 2
	#
	# param set WEST_EN 1
	#
	# param set V19_VT_ROLLDIR 0
fi
# This is special kitex VTOL ( from now it has to be always 22)
set MAV_TYPE 22
# kitex special H configuration for the mixer
set MIXER_FILE etc/mixers-sitl/kx4_vtol.main.mix
set MIXER custom
