#!/bin/sh
#
# @name KX4 VTOL
#
# @type MODIFIED VTOL
#

sh /etc/init.d/rc.vtol_defaults

if [ $AUTOCNF = yes ]
then
  param set MC_PITCH_P 6
  param set MC_PITCHRATE_P 0.2
	# param set MC_ROLL_P 6.5
	param set MC_ROLLRATE_P 0.3

	param set MIS_TAKEOFF_ALT 10
  # number of the motors of the VTOL
	param set VT_MOT_COUNT 8
  param set VT_IDLE_PWM_MC  1080
	# type of the vtol
	# 3 is KITE
	param set VT_TYPE 4
	param set RTL_DESCEND_ALT 10.0
	param set RTL_LAND_DELAY 0
  param set V19_VT_ROLLDIR 0
fi
# This is special kitex VTOL ( from now it has to be always 22)
set MAV_TYPE 22
# kitex special H configuration for the mixer
set MIXER_FILE etc/mixers-sitl/kx4_vtol.main.mix
set MIXER custom
