#!/bin/sh
#
# @name KX4 VTOL
#
# @type MODIFIED VTOL
#

sh /etc/init.d/rc.vtol_defaults
# controller updated gaines
sh /etc/init.d-posix/1120_kx4_control_params

if [ $AUTOCNF = yes ]
then
  param set MC_PITCH_P 6
  param set MC_PITCHRATE_P 0.2
	# param set MC_ROLL_P 6
	param set MC_ROLLRATE_P 0.3
  param set MC_YAW_EN 0     # With tether, we don't want to have yaw control by default
  param set MC_PITCH_C_EN	0
  param set MC_PITCH_C -0.26
  # kite.cpp heading correction
  param set VT_WIND_SPEED 4

	param set MIS_TAKEOFF_ALT 30
  # number of the motors of the VTOL
	param set VT_MOT_COUNT 8
  param set VT_IDLE_PWM_MC  1080
	# type of the vtol
	# 3 is KITE
	param set VT_TYPE 3
	param set RTL_DESCEND_ALT 10.0
	param set RTL_LAND_DELAY 0
  param set V19_VT_ROLLDIR 0

  param set MPC_LOOP_TURN_R 20
  param set MPC_PHI_C 0.785
  param set MPC_THETA_C 0.5
  param set MPC_SPHERE_EN 0 # The sphere implmentation does not currently work
  param set MPC_RESOLUTION 60
  # Stop PX4 fw_att_control and run KiteX fw_att_control
  # fw_att_control stop
  # kite_att_control start
fi
# This is special kitex VTOL ( from now it has to be always 22)
set MAV_TYPE 22
# kitex special H configuration for the mixer
set MIXER_FILE etc/mixers-sitl/kx4_with_tether.main.mix
set MIXER custom
